[project]
name = "process-mining"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.3",
    "pm4py>=2.7.12.4",
    "python-dotenv>=1.0.1",
]
